#!/usr/bin/env bash

set -eu

function usage() {
  echo "Usage: $0 {start|stop|restart|status}"
  exit 127
}

if [[ $(id -u) -ne 0 ]]; then
  echo "Must be run as root"
  exit 126
fi

if [[ $# -ne 1 ]]; then
  usage
fi

CMD="$1"
PLIST="/Library/LaunchDaemons/com.foundationdb.fdbmonitor.plist"

case "$CMD" in
  "disable")
    launchctl disable system/com.foundationdb.fdbmonitor
    ;;
  "enable")
    launchctl enable system/com.foundationdb.fdbmonitor
    ;;
  "start")
    launchctl bootstrap system "$PLIST"
    ;;
  "stop")
    launchctl bootout system "$PLIST"
    ;;
  "restart")
    launchctl bootout system  "$PLIST"
    launchctl bootstrap system/501 "$PLIST"
    ;;
  "status")
    if pgrep -q fdbmonitor; then echo "running"; else echo "halted"; fi
    ;;
  *) usage ;;
esac
